import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { Button } from '../../components/Button'
import { adminCreateJob, adminDeleteJob, adminListJobs, adminUpdateJob } from '../../features/admin/adminApi'

const blank = { title: '', location: 'Remote', employmentType: 'Full-time', summary: '', description: '', applicationUrl: '', isPublished: true }
export function AdminJobs() {
  const [jobs, setJobs] = useState([]); const [form, setForm] = useState(blank)
  const load = () => adminListJobs().then((data) => setJobs(data.jobs || []))
  useEffect(() => { load() }, [])
  async function submit(e) { e.preventDefault(); if (!form.title.trim()) return; if (form._id) await adminUpdateJob(form._id, form); else await adminCreateJob(form); setForm(blank); load(); toast.success('Job saved') }
  return <div><div className="text-xs font-semibold tracking-wide text-indigo-700">ADMIN</div><h1 className="mt-2 text-2xl font-extrabold text-slate-900">Career jobs</h1><form onSubmit={submit} className="mt-6 space-y-3 rounded-2xl bg-white p-5 ring-1 ring-slate-200"><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Job title" className="w-full rounded-xl border p-2" /><div className="grid gap-3 sm:grid-cols-2"><input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} placeholder="Location" className="rounded-xl border p-2" /><input value={form.employmentType} onChange={(e) => setForm({ ...form, employmentType: e.target.value })} placeholder="Employment type" className="rounded-xl border p-2" /></div><input value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} placeholder="Short summary" className="w-full rounded-xl border p-2" /><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Full job description" className="min-h-32 w-full rounded-xl border p-2" /><input value={form.applicationUrl} onChange={(e) => setForm({ ...form, applicationUrl: e.target.value })} placeholder="Application URL" className="w-full rounded-xl border p-2" /><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.isPublished} onChange={(e) => setForm({ ...form, isPublished: e.target.checked })} /> Published</label><div className="flex gap-2"><Button type="submit">{form._id ? 'Update job' : 'Publish job'}</Button>{form._id && <Button type="button" variant="ghost" onClick={() => setForm(blank)}>Cancel</Button>}</div></form><div className="mt-6 space-y-3">{jobs.map((job) => <div key={job._id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-white p-4 ring-1 ring-slate-200"><div><div className="font-bold">{job.title}</div><div className="text-xs text-slate-500">{job.isPublished ? 'Published' : 'Draft'} · {job.location}</div></div><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={() => setForm(job)}>Edit</Button><Button size="sm" variant="ghost" onClick={async () => { await adminDeleteJob(job._id); load() }}>Delete</Button></div></div>)}</div></div>
}
